version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_APP: monolith
      FLASK_ENV: development
      PYTHONPATH: $PWD
      FLASK_DEBUG: "true"
  redis:  
    image: "redis:alpine"
    ports:
      - "6379:6379"